"""add relationship between comment and user

Revision ID: c9d48d3d5323
Revises: a0f92d661758
Create Date: 2025-10-24 21:25:18.251657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c9d48d3d5323"
down_revision: Union[str, Sequence[str], None] = "a0f92d661758"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comment", sa.Column("author_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(
        "comment_author_id_fkey",
        "comment",
        "user",
        ["author_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("comment_author_id_fkey", "comment", type_="foreignkey")
    op.drop_column("comment", "author_id")
    # ### end Alembic commands ###
